In [13]:
using Distributions, CSV, DataFrames, LinearAlgebra, DelimitedFiles

In [2]:
p = 10
n = Int(1e5)

100000

In [3]:
# random X data.
X = randn(n, p - 1)
X = [ones(n) ;; X];

In [4]:
# generate true value of beta for LR.
β = randn(p)

10-element Vector{Float64}:
  0.574097292758785
  1.416091936759158
  0.4076501026794924
 -0.17357858841174068
  0.9875806491774863
 -0.32980765466841416
 -0.6238375815668155
  0.4040495150323981
  1.1129755593272874
  0.18462784477847924

In [5]:
function σ(x)
    return one(x) / (one(x) + exp(-x))
end

σ (generic function with 1 method)

In [6]:
p = σ.(X * β)

100000-element Vector{Float64}:
 0.882347142816194
 0.8839365048035687
 0.5279406000111281
 0.45745558668335445
 0.900924532659282
 0.9578912698468117
 0.8056746541157991
 0.8705754794842931
 0.6344599200289935
 0.7765508132171002
 0.06931668816868938
 0.9485876773916263
 0.872660652592163
 ⋮
 0.8387191894246812
 0.336585954245752
 0.8626751450392011
 0.8418978936446373
 0.10808687613619626
 0.29718741577945684
 0.7801000012665147
 0.9976397989821785
 0.5623575216772454
 0.3929746519750486
 0.23722690441393918
 0.8978128716417049

In [7]:
# generate labels
y = rand(n) .< p

100000-element BitVector:
 1
 1
 0
 1
 1
 1
 1
 1
 1
 1
 0
 1
 1
 ⋮
 1
 0
 1
 1
 1
 1
 1
 1
 1
 0
 0
 1

In [8]:
data = [X ;; y]

100000×11 Matrix{Float64}:
 1.0   0.574862    -1.0806     -0.418093   …   0.481523  -0.226299   1.0
 1.0   0.776384     0.0550471  -0.0606124      0.698078   0.066935   1.0
 1.0   1.09172     -0.631223    0.641016      -0.384765   0.600121   0.0
 1.0  -0.672052     2.43145     1.47447        0.461837  -0.576641   1.0
 1.0   0.860836    -0.164398    1.53722        0.213606  -0.035842   1.0
 1.0   0.716834    -0.276879   -0.401135   …   1.3247     0.527772   1.0
 1.0   0.467617     1.64826     0.836335      -0.109489  -0.151928   1.0
 1.0  -0.727069     0.532335   -0.811135       1.09976    0.574664   1.0
 1.0   0.457867     1.29696    -0.63014        0.141681  -0.703412   1.0
 1.0   0.0418891   -1.33147     0.189795       1.54436   -0.821029   1.0
 1.0  -1.78369     -0.914654    0.287673   …   0.93703   -0.0974948  0.0
 1.0   0.296276     1.66832    -1.01223       -1.46358    1.44381    1.0
 1.0   1.98275     -0.373838    0.447554       0.862574  -0.473345   1.0
 ⋮                      

In [9]:
CSV.write("../data/lr.csv", DataFrame(data, :auto))

"../data/lr.csv"

In [14]:
DelimitedFiles.writedlm("../data/beta.txt", β)